<script setup>
import {ref} from "vue"
// save navigation bar data
const navList = ref([])
const dataList = {
  advancedMath : [{
    "part": "P1",
    "title": "1.1 映射",
    "time": "47:15",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=1"
  }, {
    "part": "P2",
    "title": "【口误修正】Rg包含于Df",
    "time": "01:04",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=2"
  }, {
    "part": "P3",
    "title": "1.1 函数",
    "time": "12:22",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=3"
  }, {
    "part": "P4",
    "title": "1.1 函数的几种特性",
    "time": "34:20",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=4"
  }, {
    "part": "P5",
    "title": "1.1 反函数 复合函数 初等函数",
    "time": "18:56",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=5"
  }, {
    "part": "P6",
    "title": "1.2 数列极限的定义",
    "time": "32:29",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=6"
  }, {
    "part": "P7",
    "title": "1.2 收敛数列的性质",
    "time": "25:26",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=7"
  }, {
    "part": "P8",
    "title": "反三角函数介绍",
    "time": "20:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=8"
  }, {
    "part": "P9",
    "title": "1.3 函数极限",
    "time": "1:22:36",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=9"
  }, {
    "part": "P10",
    "title": "1.4 无穷小与无穷大",
    "time": "20:01",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=10"
  }, {
    "part": "P11",
    "title": "1.5 极限运算准则（修后）",
    "time": "42:04",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=11"
  }, {
    "part": "P12",
    "title": "1.6 极限存在准则 两个重要极限",
    "time": "48:48",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=12"
  }, {
    "part": "P13",
    "title": "1.7 无穷小的比较",
    "time": "32:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=13"
  }, {
    "part": "P14",
    "title": "1.8 函数的连续性与间断点",
    "time": "39:27",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=14"
  }, {
    "part": "P15",
    "title": "1.9 闭区间连续函数的性质2",
    "time": "28:03",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=15"
  }, {
    "part": "P16",
    "title": "2.1 导数定义",
    "time": "23:28",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=16"
  }, {
    "part": "P17",
    "title": "2.1 常用求导公式举例",
    "time": "34:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=17"
  }, {
    "part": "P18",
    "title": "2.1 单侧导数",
    "time": "08:32",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=18"
  }, {
    "part": "P19",
    "title": "2.1 导数的几何含义",
    "time": "16:26",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=19"
  }, {
    "part": "P20",
    "title": "练习题：导数定义 切线 法线",
    "time": "16:49",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=20"
  }, {
    "part": "P21",
    "title": "2.1 可导与连续的关系",
    "time": "09:53",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=21"
  }, {
    "part": "P22",
    "title": "2.2 求导法则（和差积商）",
    "time": "28:03",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=22"
  }, {
    "part": "P23",
    "title": "2.2 反函数的求导法则",
    "time": "39:14",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=23"
  }, {
    "part": "P24",
    "title": "复合函数求导法则",
    "time": "26:31",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=24"
  }, {
    "part": "P25",
    "title": "复合函数求导（补充）",
    "time": "03:43",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=25"
  }, {
    "part": "P26",
    "title": "导数公式表",
    "time": "12:24",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=26"
  }, {
    "part": "P27",
    "title": "高阶导数",
    "time": "32:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=27"
  }, {
    "part": "P28",
    "title": "隐函数求导",
    "time": "26:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=28"
  }, {
    "part": "P29",
    "title": "参数方程求导",
    "time": "08:49",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=29"
  }, {
    "part": "P30",
    "title": "练习：高阶导数 参数方程 隐函数求导",
    "time": "21:22",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=30"
  }, {
    "part": "P31",
    "title": "微分的定义",
    "time": "23:28",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=31"
  }, {
    "part": "P32",
    "title": "基本微分公式与法则",
    "time": "16:36",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=32"
  }, {
    "part": "P33",
    "title": "微分的几何意义",
    "time": "12:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=33"
  }, {
    "part": "P34",
    "title": "微分在近似计算中的应用",
    "time": "41:26",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=34"
  }, {
    "part": "P35",
    "title": "微分中值定理",
    "time": "21:31",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=35"
  }, {
    "part": "P36",
    "title": "柯西中值定理",
    "time": "14:54",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=36"
  }, {
    "part": "P37",
    "title": "洛必达法则",
    "time": "48:19",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=37"
  }, {
    "part": "P38",
    "title": "泰勒公式",
    "time": "44:29",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=38"
  }, {
    "part": "P39",
    "title": "函数的单调性",
    "time": "24:33",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=39"
  }, {
    "part": "P40",
    "title": "函数的凹凸性和拐点",
    "time": "19:52",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=40"
  }, {
    "part": "P41",
    "title": "极值及其求法",
    "time": "39:28",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=41"
  }, {
    "part": "P42",
    "title": "函数图形的绘制",
    "time": "1:00:50",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=42"
  }, {
    "part": "P43",
    "title": "曲率",
    "time": "29:54",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=43"
  }, {
    "part": "P44",
    "title": "不定积分的定义",
    "time": "29:44",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=44"
  }, {
    "part": "P45",
    "title": "积分表",
    "time": "14:41",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=45"
  }, {
    "part": "P46",
    "title": "抖肩舞",
    "time": "02:27",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=46"
  }, {
    "part": "P47",
    "title": "不定积分的性质",
    "time": "34:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=47"
  }, {
    "part": "P48",
    "title": "第一类换元积分法",
    "time": "1:02:03",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=48"
  }, {
    "part": "P49",
    "title": "第二类换元积分法",
    "time": "53:16",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=49"
  }, {
    "part": "P50",
    "title": "分部积分法",
    "time": "55:33",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=50"
  }, {
    "part": "P51",
    "title": "有理函数积分",
    "time": "40:39",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=51"
  }, {
    "part": "P52",
    "title": "【五-1】定积分的概念",
    "time": "46:38",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=52"
  }, {
    "part": "P53",
    "title": "【五-2】定积分的性质",
    "time": "32:15",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=53"
  }, {
    "part": "P54",
    "title": "【五-3】微积分基本公式",
    "time": "51:39",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=54"
  }, {
    "part": "P55",
    "title": "【五-4】定积分的换元法",
    "time": "1:34:25",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=55"
  }, {
    "part": "P56",
    "title": "【五-5】定积分的分部积分法",
    "time": "18:36",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=56"
  }, {
    "part": "P57",
    "title": "【五-6】无穷限的反常积分",
    "time": "26:08",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=57"
  }, {
    "part": "P58",
    "title": "【五-7】无界函数的反常积分",
    "time": "27:29",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=58"
  }, {
    "part": "P59",
    "title": "【五-8】伽马函数",
    "time": "07:01",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=59"
  }, {
    "part": "P60",
    "title": "【六-1】定积分的应用-元素法",
    "time": "16:11",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=60"
  }, {
    "part": "P61",
    "title": "【六-2】定积分应用--求面积",
    "time": "37:45",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=61"
  }, {
    "part": "P62",
    "title": "【六-3】定积分应用--求面积（二）",
    "time": "10:22",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=62"
  }, {
    "part": "P63",
    "title": "【六-4】定积分应用--求面积极坐标情形",
    "time": "05:43",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=63"
  }, {
    "part": "P64",
    "title": "【六-5】定积分应用--旋转体体积",
    "time": "1:16:42",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=64"
  }, {
    "part": "P65",
    "title": "【六-6】定积分应用--平面曲线的弧长",
    "time": "41:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=65"
  }, {
    "part": "P66",
    "title": "【新】定积分应用--物理学",
    "time": "34:13",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=66"
  }, {
    "part": "P67",
    "title": "【七-1】微分方程的基本概念",
    "time": "08:50",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=67"
  }, {
    "part": "P68",
    "title": "【七-2】可分离变量的微分方程",
    "time": "12:28",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=68"
  }, {
    "part": "P69",
    "title": "【七-3】齐次方程",
    "time": "31:20",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=69"
  }, {
    "part": "P70",
    "title": "【七-4】一阶线性微分方程",
    "time": "28:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=70"
  }, {
    "part": "P71",
    "title": "【七-5】可降阶的高阶微分方程",
    "time": "17:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=71"
  }, {
    "part": "P72",
    "title": "【七-6】常系数线性齐次微分方程",
    "time": "24:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=72"
  }, {
    "part": "P73",
    "title": "【七-7】补充证明过程（可略）",
    "time": "22:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=73"
  }, {
    "part": "P74",
    "title": "【八-1】向量及线性运算",
    "time": "40:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=74"
  }, {
    "part": "P75",
    "title": "【八-2】空间直角坐标系",
    "time": "23:16",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=75"
  }, {
    "part": "P76",
    "title": "【八-3】向量模 两点距离",
    "time": "05:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=76"
  }, {
    "part": "P77",
    "title": "【八-4】方向角方向余弦",
    "time": "45:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=77"
  }, {
    "part": "P78",
    "title": "【八-5】数量积",
    "time": "30:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=78"
  }, {
    "part": "P79",
    "title": "【八-6】向量积",
    "time": "33:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=79"
  }, {
    "part": "P80",
    "title": "【八-7】平面及其方程",
    "time": "43:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=80"
  }, {
    "part": "P81",
    "title": "【八-8】平面的一般方程",
    "time": "17:15",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=81"
  }, {
    "part": "P82",
    "title": "【八-9】两平面的夹角",
    "time": "19:50",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=82"
  }, {
    "part": "P83",
    "title": "【八-10】空间直线及其方程",
    "time": "15:02",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=83"
  }, {
    "part": "P84",
    "title": "【八-11】两直线的夹角&直线与平面的夹角",
    "time": "12:12",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=84"
  }, {
    "part": "P85",
    "title": "杂例",
    "time": "50:49",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=85"
  }, {
    "part": "P86",
    "title": "曲面及其方程",
    "time": "14:03",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=86"
  }, {
    "part": "P87",
    "title": "旋转曲面",
    "time": "29:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=87"
  }, {
    "part": "P88",
    "title": "柱面",
    "time": "07:28",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=88"
  }, {
    "part": "P89",
    "title": "二次曲面",
    "time": "32:13",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=89"
  }, {
    "part": "P90",
    "title": "空间曲线及其方程",
    "time": "26:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=90"
  }, {
    "part": "P91",
    "title": "【九-1】多元函数的基本概念--平面点集",
    "time": "23:34",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=91"
  }, {
    "part": "P92",
    "title": "【九-2】n维空间",
    "time": "09:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=92"
  }, {
    "part": "P93",
    "title": "【九-3】多元函数的极限",
    "time": "34:39",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=93"
  }, {
    "part": "P94",
    "title": "【九-4】偏导数",
    "time": "43:41",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=94"
  }, {
    "part": "P95",
    "title": "【九-6】全微分",
    "time": "46:01",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=95"
  }, {
    "part": "P96",
    "title": "【九-7】多元复合函数求导（理论讲解）",
    "time": "30:32",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=96"
  }, {
    "part": "P97",
    "title": "【九-8】多元复合函数求导（例子讲解）",
    "time": "11:59",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=97"
  }, {
    "part": "P98",
    "title": "【九-9】隐函数求导（一个方程）",
    "time": "28:31",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=98"
  }, {
    "part": "P99",
    "title": "【九-10】隐函数求导（方程组）",
    "time": "37:27",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=99"
  }, {
    "part": "P100",
    "title": "【9-10】隐函数求导（方程组）例3符号更正",
    "time": "00:21",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=100"
  }, {
    "part": "P101",
    "title": "【九-11】一元向量值函数及其导数",
    "time": "46:56",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=101"
  }, {
    "part": "P102",
    "title": "【九-12】空间曲线的切线与法平面",
    "time": "26:32",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=102"
  }, {
    "part": "P103",
    "title": "【九-13】空间曲面的切平面与法线",
    "time": "13:55",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=103"
  }, {
    "part": "P104",
    "title": "【九-14】方向导数",
    "time": "53:04",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=104"
  }, {
    "part": "P105",
    "title": "【九-15】梯度",
    "time": "30:42",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=105"
  }, {
    "part": "P106",
    "title": "【九-16】方向导数和梯度的解释",
    "time": "11:24",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=106"
  }, {
    "part": "P107",
    "title": "【九-17】梯度（例题#1）",
    "time": "14:22",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=107"
  }, {
    "part": "P108",
    "title": "【九-18】梯度（例题#2）",
    "time": "06:36",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=108"
  }, {
    "part": "P109",
    "title": "【九-19】多元函数的极值",
    "time": "20:50",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=109"
  }, {
    "part": "P110",
    "title": "【九-20】数量场向量场",
    "time": "36:46",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=110"
  }, {
    "part": "P111",
    "title": "【九-21】多元函数的最值",
    "time": "09:10",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=111"
  }, {
    "part": "P112",
    "title": "【九-22】条件极值 拉格朗日乘数法（理论讲解）",
    "time": "19:29",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=112"
  }, {
    "part": "P113",
    "title": "【九-23】极值例题",
    "time": "15:14",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=113"
  }, {
    "part": "P114",
    "title": "【十-1】二重积分的定义",
    "time": "24:21",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=114"
  }, {
    "part": "P115",
    "title": "【十-2】二重积分的性质",
    "time": "14:43",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=115"
  }, {
    "part": "P116",
    "title": "【十-3】二重积分的计算（直角坐标系）",
    "time": "1:20:22",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=116"
  }, {
    "part": "P117",
    "title": "【十-4】极坐标介绍1",
    "time": "35:25",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=117"
  }, {
    "part": "P118",
    "title": "【十-5】极坐标介绍2",
    "time": "21:32",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=118"
  }, {
    "part": "P119",
    "title": "【十-6】二重积分（极坐标）",
    "time": "58:30",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=119"
  }, {
    "part": "P120",
    "title": "【十-7】极坐标例题",
    "time": "07:13",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=120"
  }, {
    "part": "P121",
    "title": "【十-8】二重积分的换元法",
    "time": "1:00:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=121"
  }, {
    "part": "P122",
    "title": "【十-9】三重积分的定义",
    "time": "14:23",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=122"
  }, {
    "part": "P123",
    "title": "【十-10】密度均匀&&不均匀的理解",
    "time": "14:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=123"
  }, {
    "part": "P124",
    "title": "【十-11】三重积分的计算（直角坐标系）",
    "time": "35:55",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=124"
  }, {
    "part": "P125",
    "title": "【十-12】例2",
    "time": "11:12",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=125"
  }, {
    "part": "P126",
    "title": "【十-13】柱面坐标",
    "time": "30:40",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=126"
  }, {
    "part": "P127",
    "title": "【十-14】三重积分球面坐标（插入了新例题 ）",
    "time": "28:34",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=127"
  }, {
    "part": "P128",
    "title": "【十-15】三重积分的应用（求曲面的面积）新增加了证明",
    "time": "19:58",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=128"
  }, {
    "part": "P129",
    "title": "【十-16】重积分应用（求质心）",
    "time": "16:03",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=128"
  }, {
    "part": "P130",
    "title": "【十-17】重积分应用（求转动惯量）",
    "time": "04:34",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=130"
  }, {
    "part": "P131",
    "title": "【十-18】重积分应用（求引力）",
    "time": "16:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=131"
  }, {
    "part": "P132",
    "title": "【十一（1）】对弧长的曲线积分（概念与性质）",
    "time": "14:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=132"
  }, {
    "part": "P133",
    "title": "【十一（2）】曲线积分的计算",
    "time": "26:32",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=133"
  }, {
    "part": "P134",
    "title": "【十一（3）】对坐标的曲线积分（概念和性质）",
    "time": "26:08",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=134"
  }, {
    "part": "P135",
    "title": "【十一（4）】对坐标的曲线积分（计算）",
    "time": "20:44",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=135"
  }, {
    "part": "P136",
    "title": "【十一（5）】例题",
    "time": "30:08",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=136"
  }, {
    "part": "P137",
    "title": "【十一（6）】两类曲线积分的联系",
    "time": "18:01",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=137"
  }, {
    "part": "P138",
    "title": "【十一（7）】格林公式的定义和证明",
    "time": "1:02:08",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=138"
  }, {
    "part": "P139",
    "title": "【十一（8）】格林公式的计算",
    "time": "44:53",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=139"
  }, {
    "part": "P140",
    "title": "【十一（9）】对面积的曲面积分",
    "time": "1:08:13",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=140"
  }, {
    "part": "P141",
    "title": "【十一（10）】第二类曲面积分的计算及两类曲面积分的关系",
    "time": "1:33:29",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=141"
  }, {
    "part": "P142",
    "title": "【十一（11）】高斯公式 散度 通量",
    "time": "52:28",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=142"
  }, {
    "part": "P143",
    "title": "【十二（1）】常数项级数的概念和性质",
    "time": "1:10:05",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=143"
  }, {
    "part": "P144",
    "title": "【十二（2）】正项级数（一）",
    "time": "47:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=144"
  }, {
    "part": "P145",
    "title": "【十二（3）】正项级数（二）",
    "time": "1:08:51",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=145"
  }, {
    "part": "P146",
    "title": "【十二（4）】交错级数",
    "time": "25:32",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=146"
  }, {
    "part": "P147",
    "title": "【十二（5）】任意项级数",
    "time": "28:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=147"
  }, {
    "part": "P148",
    "title": "【十二（6）】幂级数（1）",
    "time": "42:17",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=148"
  }, {
    "part": "P149",
    "title": "【十二（7）】幂级数（2）",
    "time": "51:50",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=149"
  }, {
    "part": "P150",
    "title": "【十二（8）】幂级数的运算",
    "time": "15:56",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=150"
  }, {
    "part": "P151",
    "title": "【十二（9）】例题2",
    "time": "10:03",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=151"
  }, {
    "part": "P152",
    "title": "【十二（10）】函数展成幂级数（1）",
    "time": "20:57",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=152"
  }, {
    "part": "P153",
    "title": "【十二（11）】函数展成幂级数（2）",
    "time": "29:27",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=153"
  }, {
    "part": "P154",
    "title": "【十二（12）】例题讲解",
    "time": "31:10",
    "titleLink": "https://www.bilibili.com/video/BV1Eb411u7Fw/?p=154"
  }]
}
// nav list
const listData = ref([
  {'data' : "高等数学" , "key" : "1"},
  {'data' : '线性代数' , 'key' : '2'},
  {'data' : '微积分' , 'key' : '3'},
])
</script>

<template>
  <div class="main">
    <div class="list" style="margin-bottom: 40px">
      <a-tabs v-for="i  in listData" :key="i.key" :hoverable="true" style="list-style: none;float: left">
        <a-list-item style="margin-left: 400px">{{i.data}}</a-list-item>
      </a-tabs>
      <br>
    </div>


  </div>
</template>

<style scoped>

</style>